version: '3.8'
services:
  ngrx-client:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - nest-api
    # volumes: # Volume binding
    #     - './angulardockerproject:/home/node/app' 
    # command: > 
    #     bash -c "yarn install && ng serve --host 0.0.0.0 --port 4200"

  nest-api:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /home/ash/docker-mount/postgres/data:/var/lib/postgresql/data

  

volumes:
  postgres:
    name: nest_prisma_postgres
